### ISSUE TITLE
Way to trigger an analyze for use in post add scripting

### ISSUE THREAD

**Issue by merc1031** [neckbeard-io/kintro#25]
Video objects in plex have a `analyze` function that appears to block until analysis is done.

Maybe a new command to ask for an analyze of a candidate for kintro?
Or a Flag to try to generate an intro if an intro is missing (last chance behaviour)?

**Comment by merc1031** [comment]
@brutog Thoughts?

**Comment by brutog** [comment]
I was going to check plex webhooks and see what was available. It might be nice to have a kintro command to trigger analyze if that will stuff intro data into the DB for any videos that somehow didn't scrape it. Calling analyze in bulk seems dangerous though.

Webhook docs for reference:
https://support.plex.tv/articles/115002267687-webhooks/?utm_campaign=Plex%20Apps&utm_medium=Plex%20Web&utm_source=Plex%20Apps

Doesn't seem promising really.

**Comment by merc1031** [comment]
I think ill add it as an adanced feature to kintro.
Rationale:

Especially for filtered updates, would be nice to say "Hey theres no intro, try to make plex generate one"
Second use case. plex's intro filtering gets updated over time, so it might be nice to be able to have kintro poke plex to try to detect an intro that it may not have detected in the past

**Comment by brutog** [comment]
Sounds fine to me...maybe with a warning that it could be heavy if used with high parallelism.
